### PR TITLE
Less hardcoded stuff

### LINKED ISSUE #2: Remove all the hardcoded stuff
There's a _lot_ of hardcoded data at the moment, since the application was originally developed for internal usage only. To be specific, the categories where hardcoded stuff needs to be removed are:

- IP addresses, like the one at

  https://github.com/dorodere/komplett-normale-busliste/blob/c431dee2072818843bc95059a4199a65ba39571c/src/authflow.rs#L152

  which should go into `Rocket.toml`.

- Person IDs, like

  https://github.com/dorodere/komplett-normale-busliste/blob/c431dee2072818843bc95059a4199a65ba39571c/src/sql_interface.rs#L372

  which should be instead properly inserted into the database, like here a new column in the `person` table, specifying whether a person is supposed to be filtered.

- Strings, like

  https://github.com/dorodere/komplett-normale-busliste/blob/c431dee2072818843bc95059a4199a65ba39571c/templates/login.html.hbs#L26

  which... I'm not sure, to be honest. Something tells me the instance admin might want to edit the templates directly, something tells me it should go into `Rocket.toml`. Open for any hints.

### LINKED ISSUE #7: Proper local testing mode
A flag present in `Rocket.toml` or provided through other means needs to denote when the instance is switched into testing mode, in effect simply not sending emails but just printing the URL directly to stdout instead.

This basically just means adding a config option in `config.rs` and then applying this patch properly (in a way that doesn't require pre-runtime changes anymore but depends on the config option instead):

https://github.com/dorodere/komplett-normale-busliste/blob/37e479201def703088639c8a4a74ecfb6325642e/slightly-hacky-local-testing.patch#L1-L26

Currently we apply this patch manually, which is error-prone and includes the not so nice possibility of committing that one.

### PR DESCRIPTION
**Pull request by dorodere**
Closes #2.

- Whether or not a user is listed on the registration page for a drive is controllable per-user now.
  - As this needs a new column, this PR also adds a new mechanism for database updates, to build upon when versioning and creating update mechanisms.
- The slightly uncomfortable local patch to switch into testing mode is automatically done by detecting Rocket's profile now. By default `cargo run` turns on the testing mode, `cargo run --release` turns it off.
  - This is configurable at runtime using the `ROCKET_PROFILE` environment variable.
  - Testing mode turns off sending emails at the configured domain and instead just logs the login link instead.
- The outside facing address is configurable now.

### CODE REVIEW

**Comment by dorodere** [comment]
Blocking #6 which needs to be done soon-ish. As this is very likely to get merged, I'll base the branch for #6 on this.

**Comment by dorodere** [comment]
I just realized this is not finished. We can still make this better by adding a `settings` table, configurable by the enduser, for stuff like the message at the bottom of the page when logging in.

**Comment by dorodere** [comment]
Actually, no. This will be a lot more work and is mostly unrelated to the other stuff happening here. I'll open an issue with the information here and create a separate PR.

**Review by Nitro-paul — APPROVED** [review]
good work :)

**Pull request merged**
